games_store/api/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'games', views.GameViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'platforms', views.PlatformViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    re_path(r'games/(?P<pk>\d+)/thumbnail/$', views.thumbnail_image, name = "thumbnail_image"),
    path('', include(router.urls)),
]

games_store/games_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('store.urls', 'store'), namespace = 'store')),
    re_path(r'^users/', include(('users.urls', 'users'), namespace = 'users')),
    re_path(r'^library/', include(('library.urls', 'library'), namespace = 'library')),
    re_path(r'^api/', include(('api.urls', 'api'), namespace = 'api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

games_store/library/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path

from . import views


urlpatterns = [
	re_path(r'^$', views.index, name = "index"),
	re_path(r'^download/(?P<pk>\d+)/$', views.download, name = "download")
]

games_store/library/views.py
import os

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse

from store.models import Game

@login_required
def index(request):
	games = Game.objects.all().filter(owners=request.user)
	print(games)
	return render(request, "library/index.html", {"games": games})


@login_required
def download(request, pk):
	game = Game.objects.get(pk=pk)
	file_path = os.path.basename(game.game_files.name)
	print("file path {}".format(file_path))
	response = HttpResponse(game.game_files)
	response["Content-Disposition"] = "attachment; filename={}".format(file_path)
	return response

games_store/library/templates/library/index.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
	<link rel = "stylesheet" href = "{% static 'css/library.css' %}">
	<script src = "{% static 'js/game_tabs.js' %}"></script>
{% endblock %}

{% block content %}
	<div class = "row">
		<div class = "col s5 m4 l3" id = "tab-selectors"s>
			{% for game in games %}
				<a href = "#select-{{ game.pk }}">
					<div class = "tab-selector library-select-tab" id = "select-{{ game.pk }}">
						<p class = "center flow-text">{{ game.name }}</p>
					</div>
				</a>
			{% endfor %}
		</div>
		<div class = "col s7 m8 l9 tab-items">
			{% for game in games %}
				<div id = "select-{{ game.pk }}" class = "tab-item library-item padding-vert-40">
					<img src = "{{ game.get_thumbnail_url }}" align = "middle">
					<p class = "center flow-text">{{ game.name }}</p>
					<a href = "{% url 'library:download' pk=game.pk %}" class = "btn">Download</a>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}