games_store/api/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'games', views.GameViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'platforms', views.PlatformViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    re_path(r'games/(?P<pk>\d+)/thumbnail/$', views.thumbnail_image, name = "thumbnail_image"),
    path('', include(router.urls)),
]

games_store/games_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('store.urls', 'store'), namespace = 'store')),
    re_path(r'^users/', include(('users.urls', 'users'), namespace = 'users')),
    re_path(r'^library/', include(('library.urls', 'library'), namespace = 'library')),
    re_path(r'^api/', include(('api.urls', 'api'), namespace = 'api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

games_store/store/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
	re_path(r'^$', views.index, name = "index"),
	re_path(r'^game/(?P<pk>\d+)/$', views.detail, name = "detail"),
	re_path(r'^search/$', views.search, name = "search"),
	re_path(r'^buy/(?P<game_pk>\d+)/$', views.buy, name = "buy")
]

games_store/users/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
	re_path(r'^register/$', views.register, name = "register"),
	re_path(r'^login/$', views.login_view, name = "login"),
	re_path(r'^logout/$', auth_views.LogoutView.as_view(template_name="users/logout.html"), name = "logout"),
	re_path(r'^profile/(?P<pk>\d+)$', views.profile, name = "profile")
]

games_store/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Game Store</title>
	<link rel = "stylesheet" href = "{% static 'css/normalize.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/materialize.min.css' %}">
	<link rel = "stylesheet" href = "{% static 'css/main.css' %}">

	<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

	<script src = "{% static 'js/materialize.min.js' %}"></script>
	<script src = "{% static 'js/dropdown.js' %}"></script>
	{% block head %}

	{% endblock %}
</head>

<body class = "indigo darken-1">
	<div id = "navbar" class = "section indigo darken-3">
		<div class = "row">
			<div class = "col m5 s4 left-align">
				<a href = "{% url 'store:index' %}">Store</a>
				<a href = "">Help</a>
			</div>
			<div class = "col m2 s4 center-align circle" style = "max-height: 64px;">
				<a href = "{% url 'store:index' %}">
					<img src = "{% static 'images/gamepad.png' %}" id = "site-icon">
				</a>
			</div>

			<div class = "col m5 s4 right-align">
				{% if user.is_authenticated %}
					<a href = "{% url 'library:index' %}">Library</a>
					<a class = "dropdown-trigger" href = "#" data-target="profile-dropdown">Profile</a>

					<ul id = "profile-dropdown" class = "dropdown-content indigo darken-3">
						<li><a href = "{% url 'users:profile' pk=user.pk %}	">View profile</a></li>
						<li><a href = "{% url 'users:logout' %}">Logout of <span id = "dropdown-username" class = "teal-text text-lighten-3">{{ user.username }}</span></a></li>
					</ul>

				{% else %}
					<a href = "{% url 'users:register' %}">Register</a>
					<a href = "{% url 'users:login' %}">Login</a>
				{% endif %}
			</div>
		</div>
	</div>
	
	<div class = "content indigo">
		{% if messages %}
			{% for message in messages %}
				<div class = "message {{ message.tags }}">
					<p>{{ message }}</p>
				</div>
			{% endfor %}
		{% endif %}

		{% block content %}
		
		{% endblock %}
	</div>

	<footer class = "page-footer indigo darken-2">
		<div class = "footer-copyright indigo darken-3">
			<p class = "center">© 2019 Krasimir Georgiev</p>
		</div>
	</footer>
</body>
</html>