games_store/api/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'games', views.GameViewSet)
router.register(r'tags', views.TagViewSet)
router.register(r'platforms', views.PlatformViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    re_path(r'games/(?P<pk>\d+)/thumbnail/$', views.thumbnail_image, name = "thumbnail_image"),
    path('', include(router.urls)),
]

games_store/games_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path, path

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(('store.urls', 'store'), namespace = 'store')),
    re_path(r'^users/', include(('users.urls', 'users'), namespace = 'users')),
    re_path(r'^library/', include(('library.urls', 'library'), namespace = 'library')),
    re_path(r'^api/', include(('api.urls', 'api'), namespace = 'api')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

games_store/store/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
	re_path(r'^$', views.index, name = "index"),
	re_path(r'^game/(?P<pk>\d+)/$', views.detail, name = "detail"),
	re_path(r'^search/$', views.search, name = "search"),
	re_path(r'^buy/(?P<game_pk>\d+)/$', views.buy, name = "buy")
]

games_store/store/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Game(models.Model):
	name = models.CharField(max_length = 128)
	description = models.TextField()
	price = models.IntegerField()
	thumbnail = models.ImageField(upload_to = 'game_thumbnails/')
	takes_two_columns = models.BooleanField(default=False)
	game_files = models.FileField(upload_to ='games/')
	release_date = models.DateTimeField(auto_now_add = True)
	tags = models.ManyToManyField('Tag')
	platforms = models.ManyToManyField('Platform')
	owners = models.ManyToManyField(User)

	def get_thumbnail_url(self):
		return settings.MEDIA_URL + self.thumbnail.name

	def __str__(self):
		return self.name


class GameImage(models.Model):
	game = models.ForeignKey('Game', on_delete = models.CASCADE)
	image = models.ImageField(upload_to = 'game_images/')

	def get_url(self):
		return settings.MEDIA_URL + self.image.name


class Review(models.Model):
	game = models.ForeignKey('Game', on_delete = models.CASCADE)
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	title = models.CharField(max_length = 128)
	rating = models.IntegerField()
	description = models.TextField()

	def __str__(self):
		return "review for {} by {}: {}".format(self.game.name, self.user.username, self.title)


class Tag(models.Model):
	name = models.CharField(max_length = 32)

	def __str__(self):
		return self.name


class Platform(models.Model):
	name = models.CharField(max_length = 32)

	def __str__(self):
		return self.name

games_store/store/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Review


class ReviewForm(forms.Form):
	title = forms.CharField(max_length = 64, widget = forms.TextInput(attrs={"placeholder": "Title"}))
	description = forms.CharField(widget = forms.Textarea(
		attrs={"placeholder": "10/10 best game ever",
			   "class": "materialize-textarea"}
	))	
	rating = forms.IntegerField(widget = forms.HiddenInput(attrs={"id": "rating"}))	

games_store/store/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Avg
from django.core.paginator import Paginator

from .models import Game, GameImage, Tag, Review

from .forms import ReviewForm

def index(request):
	games = Game.objects.all()
	return render(request, "store/index.html", {"games": games, "MEDIA_URL": settings.MEDIA_URL })


def detail(request, pk):
	game_query = (Game.objects
		.prefetch_related("gameimage_set", "review_set", "tags", "platforms")
	)
	if request.user.is_authenticated:
		game_query.prefetch_related("owenrs")

	game = game_query.get(pk=pk)

	images = game.gameimage_set.all()
	reviews = game.review_set.select_related("user__profile").all()
	tags = game.tags.all()
	platforms = game.platforms.all()

	rating = reviews.aggregate(Avg("rating"))["rating__avg"]

	is_owner = False
	has_reviewed = False
	user_review = None
	review_form = None

	if request.user.is_authenticated:
		if game.owners.filter(id=request.user.pk):
			is_owner = True

		if reviews.filter(user=request.user.pk):
			has_reviewed = True

		if has_reviewed:
			user_review = reviews.get(user=request.user)
		
		review_form = ReviewForm()		
		if request.method == "POST":
			review_form = ReviewForm(request.POST)
			if review_form.is_valid():
				review = Review.objects.create(
					game=game,
					user=request.user,
					title=review_form.cleaned_data["title"],
					rating=review_form.cleaned_data["rating"],
					description=review_form.cleaned_data["description"],
				)
				messages.success(request, "Review added!")
				return redirect("/store/game/" + pk)

	return render(
		request, 
		"store/detail.html", 
		{"game": game, "images": images, "reviews": reviews, "tags": tags, "platforms": platforms,
		 "is_owner": is_owner, "has_reviewed": has_reviewed, "review_form": review_form, 
		 "user_review": user_review, "rating": rating}
	)


def search(request):
	games_list = Game.objects.all()
	games_per_page_count = 2
	page = 1

	if request.GET:
		print(request.GET)
		if request.GET.get("search-text"):
			games_list = games_list.filter(name__contains=request.GET["search-text"])

		if request.GET.get("tags[]"):
			for tag_id in request.GET.getlist("tags[]"):
				games_list = games_list.filter(tags__pk=tag_id)

		if request.GET.get("page"):
			page = request.GET["page"]

		if request.GET.get("count"):
			games_per_page_count = request.GET.get("count")


	paginator = Paginator(games_list, games_per_page_count)
	games = paginator.get_page(page)
	tags = Tag.objects.all()

	return render(request, "store/search_bar.html", 
		{"games": games, 
		 "tags": tags, 
		 "games_per_page_count": games_per_page_count})


@login_required
def buy(request, game_pk):
	game = Game.objects.get(pk=game_pk)
	game.owners.add(request.user)
	messages.success(request, "Succesfully bought game!")
	return redirect("/store/game/" + game_pk)

games_store/store/templates/store/detail.html
{% extends 'store/layout.html' %}
{% load static %}

{% block head %}
	<script src="https://cdn.jsdelivr.net/remarkable/1.7.1/remarkable.min.js"></script>
	<script src = "{% static 'js/markdown_render.js' %}"></script>

	<link rel = "stylesheet", href = "{% static 'css/store.css' %}">
	<script src = "{% static 'js/star_selector.js' %}"></script>

	
	
{% endblock %}

{% block content %}
	<div class = "grey-text text-lighten-3">
		<div class="parallax-container hide-on-med-and-down">
	    	<div class="parallax">
	    		<img src="{{ game.get_thumbnail_url }}">
	    	</div>
	    </div>
	    <img src = "{{ game.get_thumbnail_url }}" class = "game-image hide-on-large-only">
	    
		{% if images %}
			<div class = "indigo darken-2 items-tab">
	      		{% for image in images %}
	      			<div class = "item-tab">
		      			<img src = "{{ image.get_url }}" class = "materialboxed item-tab">
		      		</div>
		        {% endfor %}
		    </div>
	    {% endif %}

		<div class = "row margin-hor-20 margin-vert-80">
			<div id = "description-box" class = "indigo darken-2 z-depth-2 col s12 m6">
				<p>Description:</p>
				<p id = "description-text">{{ game.description }}</p>
			</div>
			<div class = "col s12 m1"></div>
			<div class = "col s12 m5 indigo darken-3 z-depth-3">
				<p id = "title">{{ game.name }}</p>
				<p id = "review-num">Reviews: {{ rating }}/5</p>
				<p id = "release-date">{{ game.release_date.date }}</p>
				<p id = "developer-link">Developer: <a href = "#to_developer">Developer link here!</a></p>
				{% if tags %}
					<p>Tags:    
						{% for tag in tags %}
							<span id = "game-tag" class = "amber-text">{{ tag.name }}</span>		
						{% endfor %}
					</p>
				{% endif %}

				{% if platforms %}
					<p>Platforms:
						{% for platform in platforms %}
							<span id = "platform"> {{ platform.name }}</span>
						{% endfor %}
					</p>
				{% endif %}
				<br>
				{% if user.is_authenticated %}
					{% if is_owner %}
						<p id = "owned">Already owned</p>
					{% else %}
						<button class = "btn"><a href = "{% url 'store:buy' game_pk=game.pk %}">Buy Game!</a></button>
					{% endif %}
				{% endif %}
			</div>
		</div>

		{% if user.is_authenticated %}
			{% if has_reviewed %}
				
				<div class = "row padding-vert-20 padding-hor-20 indigo darken-2">
					<p class = "center">Your review of the game</p>
					<div class = "col s4 m2">
						<img src = "{{ user.profile.image.url }}" class = "game-image">
						<p>{{ user.username }}</p>
					</div>
					<div class = "col s8 m9">
						<div class = "row valign-wrapper">
							<div class = "col s6 m4 l3">
								{% for _ in ''|center:user_review.rating %}
									<img src = "{% static 'images/star_filled.png' %}">
								{% endfor %}
							</div>
							<div class = "col s6 m8 l9">
								<p id = "review-title" class = "valign-wrapper">{{ user_review.title }}</p>
							</div>
						</div>
						<p>{{ user_review.description }}</p>
					</div>
				</div>
			{% else %}
			<form method = "POST" id = "review-form" class = "row input-field indigo darken-2 margin-hor-20 margin-vert-80 padding-vert-20">
				{% csrf_token %}
				<div class = "col s12 m2 l2">
					<img src = "{{ user.profile.image.url }}" class = "game-image">
					<p>Reviews: {{ user.review_set.count }}</p>
				</div>
				<div class = "col s10 m8 l8">
					<label>Leave a review</label>
					<div class = "row">
						<div class = "col s5 m5 l3">
							<div class = "star_container">
								<img src = "{% static 'images/star_unfilled.png' %}" class = "unfilled-star">
								<img src = "{% static 'images/star_filled.png' %}" class = "filled-star">
							</div>
							<div class = "star_container">
								<img src = "{% static 'images/star_unfilled.png' %}" class = "unfilled-star">
								<img src = "{% static 'images/star_filled.png' %}" class = "filled-star">
							</div>
							<div class = "star_container">
								<img src = "{% static 'images/star_unfilled.png' %}" class = "unfilled-star">
								<img src = "{% static 'images/star_filled.png' %}" class = "filled-star">
							</div>
							<div class = "star_container">
								<img src = "{% static 'images/star_unfilled.png' %}" class = "unfilled-star">
								<img src = "{% static 'images/star_filled.png' %}" class = "filled-star">
							</div>
							<div class = "star_container">
								<img src = "{% static 'images/star_unfilled.png' %}" class = "unfilled-star">
								<img src = "{% static 'images/star_filled.png' %}" class = "filled-star">
							</div>
							
							{{ review_form.rating.errors }}
							{{ review_form.rating }}
						</div>
						<div class = "col s7 m7 l9">
							{{ review_form.title.errors }}
							{{ review_form.title }}
						</div>
					</div>
					{{ review_form.description.errors }}
					{{ review_form.description }}
					<div class = "right-align">
						<button id = "submit-btn" class = "btn" type = "submit" name = "action">Submit</button>
					</div>
	        	</div>
			</form>
			{% endif %}
		{% endif %}

		<br>
		<br>

		<div id = "reviews-list" class = "margin-hor-20">
			{% for review in reviews %}
				<div class = "row padding-vert-20 padding-hor-20 indigo darken-2">
					<div class = "col s4 m2">
						<img src = "{{ review.user.profile.image.url }}" class = "game-image">
						<p>{{ review.user }}</p>
						<p>Review count: {{ review.user.review_set.count }}</p>
						{% if game in review.user.game_set %}
							<p>Owns game</p>
						{% else %}
							<p>Purchase not verified</p>
						{% endif %}
					</div>
					<div class = "col s8 m9">
						<div class = "row valign-wrapper">
							<div class = "col s6 m4 l3">
								{% for _ in ''|center:review.rating %}
									<img src = "{% static 'images/star_filled.png' %}">
								{% endfor %}
							</div>
							<div class = "col s6 m8 l9">
								<p id = "review-title" class = "valign-wrapper">{{ review.title }}</p>
							</div>
						</div>
						<p>{{ review.description }}</p>
					</div>
				</div>

			{% endfor %}
		</div>
	</div>


	<!-- <script src = "{% static 'js/tabs.js' %}"></script> -->
	<script src = "{% static 'js/paralax.js' %}"></script> 
	<script src = "{% static 'js/materialbox.js' %}"></script>
{% endblock %}

games_store/store/templates/store/index.html
{% extends 'store/layout.html' %}
{% load static %}

{% block head %}
	<link rel = "stylesheet", href = "{% static 'css/store.css' %}">
	<script src = "{% static 'js/uniform_image_size.js' %}"></script>

{% endblock %}

{% block content %}

	<div class = "container">
		<form action = "/store/search/", method = "GET" name = "search-game" id = "search-game">
			<div class = "row padding-vert-20">
				<div class = "col s12">
					<input id = "search-text" type = "text" name = "search-text" placeholder="search games">
					<button type = "submit" class = "btn-small">Search</button>
				</div>
			</div>
		</form>
		
		<div id = "games-list" class = "row">
		{% for game in games %}
			{% if not game.takes_two_columns %}
				<div id = "game-store-box" class = "col s12 m6 l4">
					<a href = "{% url 'store:detail' pk=game.pk %}">
						<p class = "game-title">{{ game.name }}</p>
						<img src = "{{ game.get_thumbnail_url }}" class = "game-image">
					</a>
				</div>
			{% else %}
				<div id = "game-store-box" class = "col s12 m12 l8">
					<a href = "{% url 'store:detail' pk=game.pk %}">
						<p class = "game-title">{{ game.name }}</p>
						<img src = "{{ game.get_thumbnail_url }}" class = "game-image">
					</a>
				</div>
			{% endif %}
		{% endfor %}
		</div>
	</div>
	
{% endblock %}

games_store/store/templates/store/layout.html
{% extends 'layout.html' %}

{% block content %}
{% endblock %}

games_store/store/templates/store/search_bar.html
{% extends 'store/layout.html' %}
{% load static %}


{% block head %}
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{% endblock %}

{% block content %}
	
	<div class = "container">
		<form action = "/store/search/", method = "GET" name = "search-game" id = "search-game">
			<div class = "row padding-vert-20">
				<div class = "col s12 m7 l8">
					<input id = "search-text" type = "text" name = "search-text" placeholder="search games">
					<button type = "submit" class = "align-right btn-small">Search</button>

					{% if games %}
					<div id = "game-list-compact" class = "margin-vert-40">
						{% for game in games %}
							<div id = "game-box-compact">
								<a href = "{% url 'store:detail' game.pk %}">
									<div class = "row">
										<img src = "{{ game.get_thumbnail_url }}" width = 200 class = "col s4 m4 l3">
										<p class = "col s8 m8 l9">{{ game.name }}</p>
									</div>
								</a>
							</div>
						{% endfor %}
					</div>
					{% else %}
						<p>No games found!</p>
					{% endif %}
					<br>
					<ul class="pagination center">
						{% if games.has_previous %}
					    	<li><a href="?page=1&count={{ games_per_page_count }}"><i class="material-icons">chevron_left</i></a></li>
					    	<li class = "waves-effect"><a href="?page={{ games.previous_page_number }}&count={{ games_per_page_count }}">{{ games.previous_page_number }}</a></li>
					    {% endif %}
					    <li class="active waves-effects"><a href="">{{ games.number }}</a></li>
					    {% if games.has_next %}
						    <li class="waves-effect"><a href="?page={{ games.next_page_number }}&count={{ games_per_page_count }}">{{ games.next_page_number }}</a></li>
						    <li><a href="?page={{ games.paginator.num_pages }}&count={{ games_per_page_count }}"><i class="material-icons">chevron_right</i></a></li>
					    {% endif %}
					</ul>
				</div>
				<div class = "col s1"></div>
				<div class = "col s12 m4 l3">
					{% for tag in tags %}
						<p>
							<label>
						    	<input type="checkbox" name = "tags[]" value = "{{ tag.id }}"/>
						    	<span>{{ tag }}</span>
						    </label>
						</p>	
					{% endfor %}
				</div>
			</div>
		</form>
	</div>
{% endblock %}